spring:
  application:
    name:
      kafka_consumer

  kafka:
    bootstrap-servers: 192.168.0.2:9092
    consumer:
      group-id: group1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver

server:
  port: 8181