spring:
  application:
    name: api

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver

server:
  port: 8282