services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'

  redis:
    container_name: redis
    image: redis:7.0.4-alpine
    ports:
      - "6379:6379"